# Generated by Django 4.2.2 on 2023-06-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('ID_invitado', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Juntas',
            fields=[
                ('ID_junta', models.IntegerField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=255)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='JuntasInvitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.invitados')),
                ('ID_junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.juntas')),
            ],
            options={
                'unique_together': {('ID_junta', 'ID_invitado')},
            },
        ),
    ]
